Trilha 6: Gradient Boosting<br/>
O problema do Câncer (da trilha 5) com novo algoritmo

In [18]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier

In [2]:
#Obtendo o Dataset
data = load_breast_cancer()
X=data['data']
y=data['target']

In [4]:
X[:1],y[:1]#  primeira linha do dataset e do target

(array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
         3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
         8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
         3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
         1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]]),
 array([0]))

In [5]:
#Nomes das Features
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [6]:
data['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [7]:
#standardização das features (muitas ordens de grandeza diferentes)
scaler=StandardScaler()
XS=scaler.fit_transform(X)

In [8]:
XS[:1]

array([[ 1.09706398, -2.07333501,  1.26993369,  0.9843749 ,  1.56846633,
         3.28351467,  2.65287398,  2.53247522,  2.21751501,  2.25574689,
         2.48973393, -0.56526506,  2.83303087,  2.48757756, -0.21400165,
         1.31686157,  0.72402616,  0.66081994,  1.14875667,  0.90708308,
         1.88668963, -1.35929347,  2.30360062,  2.00123749,  1.30768627,
         2.61666502,  2.10952635,  2.29607613,  2.75062224,  1.93701461]])

In [13]:
#Split train test
X_train, X_test, y_train, y_test = train_test_split(
    XS, y, test_size=0.3,stratify=y,random_state=51)

In [19]:
#criação do modelo Gradient Boosting
gb=GradientBoostingClassifier(n_estimators=100,random_state=51)
gb

GradientBoostingClassifier(random_state=51)

In [20]:
#Treinamento do modelo com Gradient Boosting
gb.fit(X_train,y_train)

GradientBoostingClassifier(random_state=51)

In [21]:
#avaliação Gradient Boosting
yerf=gb.predict(X_test)
print('Gradient Boosting')
print('acurácia=',accuracy_score(y_test,yerf))
print('precision=',precision_score(y_test,yerf,pos_label=0))
print('recall=',recall_score(y_test,yerf,pos_label=0))

Gradient Boosting
acurácia= 0.9473684210526315
precision= 0.9104477611940298
recall= 0.953125


In [22]:
#Acurácia no treino: Gradient Boosting
yet=gb.predict(X_train)
accuracy_score(y_train,yet)

1.0